### ISSUE TITLE
[Question] mTLS for nomad and consul.

### ISSUE THREAD

**Issue by blmhemu** [perrymanuk/hashi-homelab#29]
I like the way you bypassed vault for secrets. But I was wondering how you managed the mTLS for nomad and consul agents.

**Comment by perrymanuk** [comment]
Nice catch there 😄 
I actually removed the tls from the api endpoints when I removed vault as I didn't want to have to manually generate and distribute the certs. I know its probably not "best practice" to do so but I don't publicly expose any of my nomad endpoints and only bind them to my tailscale interfaces and/or internal network. 🙃 

I might add vault back in at some point with an auto unseal. The only reason I really removed it was because I wanted the lab to recover fully from a full outage (loss of power at home for example) on its own. When vault was in use I had to always unseal vault before any of the jobs using its secrets could deploy.
